# K8S / Harness
envName: <+env.name>
appName: <+service.name>
artifactImage: <+artifact.image> #from Harness Service Primary Artifact
containerPort: <+serviceVariables.containerPort>
servicePort: 80
namespace: <+service.name>-<+env.name>
ingressDomainName: <+serviceVariables.ingressDomainName>
CorsOrigin: <+serviceVariables.CorsOrigin>

# Database
MYSQL_USER: <+serviceVariables.MYSQL_USER>
MYSQL_PASSWORD: <+serviceVariables.MYSQL_PASSWORD>
MYSQL_PORT: <+serviceVariables.MYSQL_PORT>
MYSQL_HOST: <+serviceVariables.MYSQL_HOST>
MYSQL_TABLE: <+serviceVariables.MYSQL_TABLE>
MYSQL_DATABASE: <+serviceVariables.MYSQL_DATABASE>

# Recaptcha
RECAPTCHA: <+serviceVariables.RECAPTCHA>

# Public keys
PUBLIC_KEYS: <+serviceVariables.PUBLIC_KEYS>