apiVersion: v1
kind: ConfigMap
metadata:
  name: {{.Values.appName}}-{{.Values.envName}}-config
  namespace: {{.Values.namespace}}
data:
  # Database
  MYSQL_USER: {{.Values.MYSQL_USER}}
  MYSQL_PASSWORD: {{.Values.MYSQL_PASSWORD}}
  MYSQL_PORT: {{.Values.MYSQL_PORT}}
  MYSQL_HOST: {{.Values.MYSQL_HOST}}
  MYSQL_TABLE: {{.Values.MYSQL_TABLE}}
  MYSQL_DATABASE: {{.Values.MYSQL_DATABASE}}
  # Recaptcha
  RECAPTCHA_SECRET_KEY: {{.Values.RECAPTCHA_SECRET_KEY}}
  # Public keys
  PUBLIC_KEYS: {{.Values.PUBLIC_KEYS}}    
  # React
  REACT_APP_BACKEND_URL: {{.Values.REACT_APP_BACKEND_URL}}
  REACT_APP_BACKEND_PORT: {{.Values.REACT_APP_BACKEND_PORT}}
  REACT_APP_RECAPTCHA_CLIENT_KEY: {{.Values.REACT_APP_RECAPTCHA_CLIENT_KEY}}
  

